In [1]:
import numpy as np

In [2]:
a = np.arange(9 , dtype = np.float_).reshape(3,3)

print("First Array :")
print(a)
print("\n")

print("Second Array :")
b = np.array([10,10,10])
print(b)
print("\n")

print("Add two Arrays :")
print(np.add(a,b))
print("\n")

print("Subtract two Arrays :")
print(np.subtract(a,b))
print("\n")

print("Multiply two Arrays :")
print(np.multiply(a,b))
print("\n")

print("Divide two Arrays :")
print(np.divide(a,b))


First Array :
[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


Second Array :
[10 10 10]


Add two Arrays :
[[10. 11. 12.]
 [13. 14. 15.]
 [16. 17. 18.]]


Subtract two Arrays :
[[-10.  -9.  -8.]
 [ -7.  -6.  -5.]
 [ -4.  -3.  -2.]]


Multiply two Arrays :
[[ 0. 10. 20.]
 [30. 40. 50.]
 [60. 70. 80.]]


Divide two Arrays :
[[0.  0.1 0.2]
 [0.3 0.4 0.5]
 [0.6 0.7 0.8]]


### numpy.reciprocal()

In [3]:
a = np.array([0.25 , 1.33 , 1, 0 ,100])

print("Our array is :")
print(a)
print("\n")

print("After applying reciprocal function :")
print(np.reciprocal(a))
print("\n")

b = np.array([100], dtype= int)

print("Second array is :")
print(b)
print("\n")

print("After applying reciprocal function :")
print(np.reciprocal(b))

Our array is :
[  0.25   1.33   1.     0.   100.  ]


After applying reciprocal function :
[4.        0.7518797 1.              inf 0.01     ]


Second array is :
[100]


After applying reciprocal function :
[0]


C:\Users\SC\AppData\Local\Temp\ipykernel_624\3685356960.py:8: RuntimeWarning: divide by zero encountered in reciprocal
  print(np.reciprocal(a))


### numpy.power()

In [4]:
a = np.array([10,100,1000])

print("Our array is :")
print(a)
print("\n")

print("Applying power function :")
print(np.power(a,2))
print("\n")

print("Second array is :")
b = np.array([1,2,3])
print(b)
print("\n")

print("After applying power function :")
print(np.power(a,b))

Our array is :
[  10  100 1000]


Applying power function :
[    100   10000 1000000]


Second array is :
[1 2 3]


After applying power function :
[        10      10000 1000000000]


### numpy.mod()

In [5]:
a = np.array([10,20,30])
b = np.array([3,5,7])

print("First array is :")
print(a)
print("\n")

print("Second array is :")
print(b)
print("\n")

print("Applying mod() function :")
print(np.mod(a,b))
print("\n")

print("Applying remainder() function :")
print(np.remainder(a,b))


First array is :
[10 20 30]


Second array is :
[3 5 7]


Applying mod() function :
[1 0 2]


Applying remainder() function :
[1 0 2]


In [6]:
a = np.array([-5.6j,0.2j,11.,1+1j])

print("Our array is :")
print(a)
print("\n")

print("Applying real() Function")
print(np.real(a))
print("\n")

print("Applying imag() Function")
print(np.imag(a))
print("\n")

print("Applying conj() Function")
print(np.conj(a))
print("\n")

print("Applying angle() Function")
print(np.angle(a))
print("\n")

print(" A pplying angle function again (result in degrees)")
print(np.angle(a, deg= True))

Our array is :
[-0.-5.6j  0.+0.2j 11.+0.j   1.+1.j ]


Applying real() Function
[-0.  0. 11.  1.]


Applying imag() Function
[-5.6  0.2  0.   1. ]


Applying conj() Function
[-0.+5.6j  0.-0.2j 11.-0.j   1.-1.j ]


Applying angle() Function
[-1.57079633  1.57079633  0.          0.78539816]


 A pplying angle function again (result in degrees)
[-90.  90.   0.  45.]
