In [1]:
import numpy as np

#### numpy.amax() and numpy.amin()

In [2]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

print("Our array is :")
print(a)
print("\n")

print("Applying amin() function :")
print(np.amin(a,1))
print("\n")

print("Applying amin() function again :")
print(np.amin(a,0))
print("\n")

print("Applying amax() function :")
print(np.amax(a))
print("\n")

print("Applying amax() function again :")
print(np.amax(a,axis=0))

Our array is :
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying amin() function :
[3 3 2]


Applying amin() function again :
[2 4 3]


Applying amax() function :
9


Applying amax() function again :
[8 7 9]


#### np.ptp()

In [3]:
a = np.array([[3,7,5],[8,4,3],[2,4,9]])

print("Our array is :")
print(a)
print("\n")

print("Applying ptp() function :")
print(np.ptp(a))
print("\n")

print("Applying ptp() function along axis 1 :")
print(np.ptp(a, axis=1))
print("\n")

print("Applying ptp() function along axis 0 :")
print(np.ptp(a, axis=0))

Our array is :
[[3 7 5]
 [8 4 3]
 [2 4 9]]


Applying ptp() function :
7


Applying ptp() function along axis 1 :
[4 5 7]


Applying ptp() function along axis 0 :
[6 3 6]


#### np.percentile()

In [6]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

print("Our array is :")
print(a)
print("\n")

print("Applying percentile() function :")
print(np.percentile(a,50))
print("\n")

print("Applying percentile() function along axis 1 :")
print(np.percentile(a,50, axis=1))
print("\n")

print("Applying percentile() function along axis 0 :")
print(np.percentile(a,50,axis=0))


Our array is :
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying percentile() function :
50.0


Applying percentile() function along axis 1 :
[40. 20. 60.]


Applying percentile() function along axis 0 :
[50. 40. 60.]


#### np.median()

In [7]:
a = np.array([[30,40,70],[80,20,10],[50,90,60]])

print("Our array is :")
print(a)
print("\n")

print("Applying median() function :")
print(np.median(a))
print("\n")

print("Applying percentile() function along axis 1 :")
print(np.median(a,axis=1))
print("\n")

print("Applying median() function along axis 0 :")
print(np.median(a,axis=0))


Our array is :
[[30 40 70]
 [80 20 10]
 [50 90 60]]


Applying median() function :
50.0


Applying percentile() function along axis 1 :
[40. 20. 60.]


Applying median() function along axis 0 :
[50. 40. 60.]


#### np.mean()

In [9]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print("Our array is :")
print(a)
print("\n")

print("Applying mean() function :")
print(np.mean(a))
print("\n")

print("Applying mean() function along axis 1 :")
print(np.mean(a,axis=1))
print("\n")

print("Applying mean() function along axis 0 :")
print(np.mean(a,axis=0))

Our array is :
[[1 2 3]
 [3 4 5]
 [4 5 6]]


Applying mean() function :
3.6666666666666665


Applying mean() function along axis 1 :
[2. 4. 5.]


Applying mean() function along axis 0 :
[2.66666667 3.66666667 4.66666667]


#### Standard Deviation

In [10]:
# std = sqrt(mean(abs(x - x.mean())**2))

print(np.std([1,2,3,4]))

1.118033988749895


#### Variance

In [11]:
print(np.var([1,2,3,4]))

1.25
