### Q1:

In [1]:
import numpy as np
 
 
rates = [
    [1.97, 1.04, 1.35, 2.17, 2.29, 4.38],
    [1.34, 2.04, 1.37, 2.09, 1.29, 3.38],
]
 
arr = np.asarray(rates)
print(arr)

[[1.97 1.04 1.35 2.17 2.29 4.38]
 [1.34 2.04 1.37 2.09 1.29 3.38]]


### Q2:

In [2]:
import numpy as np
 
 
title = '30 Days of Python Code - Numpy Challange'
tokens = title.split(' ')
arr = np.asarray(tokens).reshape(2, -1)
 
print(arr)

[['30' 'Days' 'of' 'Python']
 ['Code' '-' 'Numpy' 'Challange']]


### Q3:

In [3]:
import numpy as np
 
 
arr = np.tile(np.arange(10), (5, 1))
 
print(arr)

[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]


### Q4:

In [4]:
import numpy as np
 
 
arr = np.array(
    [
        [[3, 2, 4, 0, 1, 3], [5, 0, 4, 4, 4, 1], [3, 2, 4, 1, 1, 4]],
        [[5, 5, 4, 5, 1, 3], [2, 2, 5, 2, 4, 0], [5, 1, 3, 4, 2, 3]],
    ]
)
 
result = np.ones_like(arr)
print(result)

[[[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]

 [[1 1 1 1 1 1]
  [1 1 1 1 1 1]
  [1 1 1 1 1 1]]]


### Q5:

In [5]:
import numpy as np
 
 
arr = np.concatenate(
    (
        np.linspace(0, 1, 11).reshape(1, -1),
        np.zeros((4, 11)),
    ),
    axis=0,
)
print(arr)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]]


### Q6:

In [6]:
import numpy as np
 
 
x = np.linspace(0, 1, 11)
y = np.linspace(0, 1, 11)
 
xx, yy = np.meshgrid(x, y)
 
print(xx)
print(yy)

[[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
 [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]]
[[0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0. ]
 [0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1 0.1]
 [0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2]
 [0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3 0.3]
 [0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.4]
 [0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]
 [0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6 0.6]
 [0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7 0.7]
 [0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8 0.8]
 [0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9 0.9]
 [1.  1.  1.

### Q7:

In [7]:
import numpy as np
 
 
string_data = '4 2 6 2 7 10 6 2 14'
arr = np.fromstring(string_data, dtype='int16', sep=' ')
 
print(arr)

[ 4  2  6  2  7 10  6  2 14]


### Q8:

In [9]:
import numpy as np
 
 
arr = np.array(
    [
        [
            [0.0, 2.0, 0.5, 1.0],
            [0.0, 2.0, 0.0, 3.0],
            [0.0, 4.0, 0.0, 0.0],
        ],
        [
            [0.0, 0.5, 0.0, 0.2],
            [0.0, 0.4, 0.0, 5.0],
            [0.0, 0.0, 1.0, 0.0],
        ],
    ],
    dtype='float32',
)

print(arr)

[[[0.  2.  0.5 1. ]
  [0.  2.  0.  3. ]
  [0.  4.  0.  0. ]]

 [[0.  0.5 0.  0.2]
  [0.  0.4 0.  5. ]
  [0.  0.  1.  0. ]]]
