In [2]:
import numpy as np

In [3]:
a = np.arange(10)
s = slice(2,7,2)
print(a[s])


[2 4 6]


In [4]:
a = np.arange(10)
b = a[2:7:2]
print(b)

[2 4 6]


In [5]:
a = np.arange(10)
b = a[5]
print(b)

5


In [6]:
a = np.arange(10)
b = a[2:]
print(b)

[2 3 4 5 6 7 8 9]


In [7]:
a = np.arange(10)
b = a[2:5]
print(b)

[2 3 4]


In [8]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])
print(a)

[[1 2 3]
 [3 4 5]
 [4 5 6]]


In [9]:
print(a[1:])

[[3 4 5]
 [4 5 6]]


In [10]:
a = np.array([[1,2,3],[3,4,5],[4,5,6]])

print("Our array is :")
print(a)
print('\n')

print("The items in second column are :")
print(a[...,1])
print('\n')

print("The items in second row are :")
print(a[1,...])
print('\n')

print("The items column 1 onwards are :")
print(a[...,1:])


Our array is :
[[1 2 3]
 [3 4 5]
 [4 5 6]]


The items in second column are :
[2 4 5]


The items in second row are :
[3 4 5]


The items column 1 onwards are :
[[2 3]
 [4 5]
 [5 6]]


### Integer Indexing

In [11]:
x = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11]])

print(x)

rows = np.array([[0,0],[3,3]])
print(rows)

cols = np.array([[0,2],[0,2]])
print(cols)

y = x[rows,cols]
print(y)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[0 0]
 [3 3]]
[[0 2]
 [0 2]]
[[ 0  2]
 [ 9 11]]


In [13]:
x = np.array([[1,2],[3,4],[5,6]])
y = x[[0,1,2],[0,1,0]]
print(y)

[1 4 5]
