### Q1:

In [1]:
import numpy as np
 
 
arr = np.array([[4, 2, 1], [6, 4, 2]])
arr = np.expand_dims(arr, axis=0)
 
print(arr)

[[[4 2 1]
  [6 4 2]]]


### Q2:

In [2]:
import numpy as np
 
 
image = np.random.randint(
    low=0, 
    high=256, 
    size=(200, 300, 3), 
    dtype=np.uint8
)
image_extended = np.expand_dims(image, axis=0)

### Q3:

In [3]:
import numpy as np
 
 
image1 = np.random.randint(
    low=0, 
    high=256, 
    size=(200, 300, 3), 
    dtype=np.uint8
)
image2 = np.random.randint(
    low=0, 
    high=256, 
    size=(200, 300, 3), 
    dtype=np.uint8
)
 
image1 = np.expand_dims(image1, axis=0)
image2 = np.expand_dims(image2, axis=0)
 
images = np.append(image1, image2, axis=0)


### Q4:

In [5]:
import numpy as np
 
 
arr = np.array([[[1, 2, 3], [6, 3, 2]]])
arr = np.squeeze(arr)
 
print(arr)

[[1 2 3]
 [6 3 2]]


### Q5:

In [6]:
import numpy as np
 
 
arr = np.array([[0.4], [0.9], [0.5], [0.6]])
arr = np.squeeze(arr)
 
print(arr)

[0.4 0.9 0.5 0.6]


### Q6:

In [7]:
import numpy as np
 
 
arr = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)
 
arr = np.ravel(arr)
print(arr)

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


### Q7:

In [8]:
import numpy as np
 
 
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
 
row = arr[np.newaxis, :]
column = arr[:, np.newaxis]
 
print(row)
print(column)

[[0 1 2 3 4 5 6 7 8 9]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### Q8:

In [9]:
import numpy as np
 
 
arr = np.full((10, 4), fill_value=False)
arr = arr.reshape(5, 2, 4)
print(arr)

[[[False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]]

 [[False False False False]
  [False False False False]]]
