## Pandas

#### * Data Analysis Library
#### * Series =  Single Dimension
#### * DataFrame = Multidimensional

In [68]:
import pandas as pd

In [69]:
s1 = pd.Series([1,2,3,4,5])

In [70]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [71]:
type(s1)

pandas.core.series.Series

In [72]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [73]:
s1.values

array([1, 2, 3, 4, 5], dtype=int64)

In [74]:
s2 = pd.Series([11,22,33,44,55], index=["a","b","c","d","e"])

In [75]:
s2

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [76]:
s1 + s2

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [77]:
s3 = pd.Series(range(10))

In [78]:
s3

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [79]:
s4 = pd.Series(range(10,20))

In [80]:
s4

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [81]:
s3 + s4

0    10
1    12
2    14
3    16
4    18
5    20
6    22
7    24
8    26
9    28
dtype: int64

In [82]:
import numpy as np

In [83]:
arr1 = np.arange(5)

In [84]:
arr1

array([0, 1, 2, 3, 4])

In [85]:
arr2 = np.arange(7)

In [86]:
arr2

array([0, 1, 2, 3, 4, 5, 6])

In [87]:
arr1 + arr2
# Returns error because both arrays are of different shapes

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [ ]:
s2[1:4]

b    22
c    33
d    44
dtype: int64

### Lambda Functions : Anonymous Functions (IIF)

In [93]:
new = pd.Series([12,23,44,56,43,57,], index=["Abdul","Farhan","Asad","Hamza","Subhan","Abdullah"])

new

Abdul       12
Farhan      23
Asad        44
Hamza       56
Subhan      43
Abdullah    57
dtype: int64

In [94]:
def myfunc(marks):
    return marks/100

In [95]:
new = new.apply(myfunc)

In [96]:
new = new.apply(lambda x: np.where(x>40, "Pass","Fail"))

In [97]:
new

Abdul       Fail
Farhan      Fail
Asad        Fail
Hamza       Fail
Subhan      Fail
Abdullah    Fail
dtype: object

In [98]:
a = np.linspace(1,10,11)

In [99]:
a

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1, 10. ])

In [100]:
new.count()

6

In [101]:
new.value_counts()

Fail    6
Name: count, dtype: int64

In [102]:
s7 = ([11,2,3,np.nan,np.nan,6])

In [103]:
s7

[11, 2, 3, nan, nan, 6]

### Pandas Data Frame