## Pandas

#### * Data Analysis Library
#### * Series =  Single Dimension
#### * DataFrame = Multidimensional

In [1]:
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4,5])

In [3]:
s1

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [4]:
type(s1)

pandas.core.series.Series

In [5]:
s1.index

RangeIndex(start=0, stop=5, step=1)

In [6]:
s1.values

array([1, 2, 3, 4, 5], dtype=int64)

In [7]:
s2 = pd.Series([11,22,33,44,55], index=["a","b","c","d","e"])

In [8]:
s2

a    11
b    22
c    33
d    44
e    55
dtype: int64

In [9]:
s1 + s2

0   NaN
1   NaN
2   NaN
3   NaN
4   NaN
a   NaN
b   NaN
c   NaN
d   NaN
e   NaN
dtype: float64

In [10]:
s3 = pd.Series(range(10))

In [11]:
s3

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64

In [12]:
s4 = pd.Series(range(10,20))

In [13]:
s4

0    10
1    11
2    12
3    13
4    14
5    15
6    16
7    17
8    18
9    19
dtype: int64

In [14]:
s3 + s4

0    10
1    12
2    14
3    16
4    18
5    20
6    22
7    24
8    26
9    28
dtype: int64

In [15]:
import numpy as np

In [16]:
arr1 = np.arange(5)

In [17]:
arr1

array([0, 1, 2, 3, 4])

In [18]:
arr2 = np.arange(7)

In [19]:
arr2

array([0, 1, 2, 3, 4, 5, 6])

In [21]:
arr1 + arr2
# Returns error because both arrays are of different shapes

ValueError: operands could not be broadcast together with shapes (5,) (7,) 

In [23]:
s2[1:4]

b    22
c    33
d    44
dtype: int64