In [1]:
import numpy as np

## Numpy_Assignment_2:

### Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired Output

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
original_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape the array to a 2D array with 2 rows
new_array = original_array.reshape(2, -1)

print(new_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [7]:
array1 = np.array([[0, 1, 2, 3, 4],
                   [5, 6, 7, 8, 9]])

array2 = np.array([[1, 1, 1, 1, 1],
                   [1, 1, 1, 1, 1]])

# Stack the arrays vertically
result_array = np.vstack((array1, array2))

print(result_array)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [8]:
array1 = np.array([[0, 1, 2, 3, 4],
                   [5, 6, 7, 8, 9]])

array2 = np.array([[1, 1, 1, 1, 1],
                   [1, 1, 1, 1, 1]])

# Stack the arrays horizontally
result_array = np.hstack((array1, array2))

print(result_array)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
array_of_arrays = np.array([[0, 1, 2, 3, 4],
                             [5, 6, 7, 8, 9]])

# Convert the array of arrays to a flat 1D array
flat_array = np.concatenate(array_of_arrays)

print(flat_array)

[0 1 2 3 4 5 6 7 8 9]


### Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [10]:
higher_dimensional_array = np.array([[0, 1, 2, 3, 4],
                                     [5, 6, 7, 8, 9],
                                     [10, 11, 12, 13, 14]])

# Use ravel() function
flattened_array = higher_dimensional_array.ravel()

# Alternatively, you can use flatten() method
# flattened_array = higher_dimensional_array.flatten()

print(flattened_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
