In [2]:
import numpy as np

## Numpy_Assignment_2:

### Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired Output

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [3]:
original_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape the array to a 2D array with 2 rows
new_array = original_array.reshape(2, -1)

print(new_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


### Question:2

###  How to stack two arrays vertically?

#### Desired Output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [4]:
array1 = np.array([[0, 1, 2, 3, 4],
                   [5, 6, 7, 8, 9]])

array2 = np.array([[1, 1, 1, 1, 1],
                   [1, 1, 1, 1, 1]])

# Stack the arrays vertically
result_array = np.vstack((array1, array2))

print(result_array)

[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


### Question:3

### How to stack two arrays horizontally?

#### Desired Output::

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [5]:
array1 = np.array([[0, 1, 2, 3, 4],
                   [5, 6, 7, 8, 9]])

array2 = np.array([[1, 1, 1, 1, 1],
                   [1, 1, 1, 1, 1]])

# Stack the arrays horizontally
result_array = np.hstack((array1, array2))

print(result_array)

[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


### Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
array_of_arrays = np.array([[0, 1, 2, 3, 4],
                             [5, 6, 7, 8, 9]])

# Convert the array of arrays to a flat 1D array
flat_array = np.concatenate(array_of_arrays)

print(flat_array)

[0 1 2 3 4 5 6 7 8 9]


### Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

In [7]:
higher_dimensional_array = np.array([[0, 1, 2, 3, 4],
                                     [5, 6, 7, 8, 9],
                                     [10, 11, 12, 13, 14]])

# Use ravel() function
flattened_array = higher_dimensional_array.ravel()

# Alternatively, you can use flatten() method
# flattened_array = higher_dimensional_array.flatten()

print(flattened_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


### Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

array([[ 0, 1, 2],
[ 3, 4, 5],
[ 6, 7, 8],
[ 9, 10, 11],
[12, 13, 14]])

In [8]:
one_dimensional_array = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])

# Reshape the array to a 2D array with 5 rows and 3 columns
result_array = one_dimensional_array.reshape(5, 3)

print(result_array)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


### Question:7

### Create 5x5 an array and find the square of an array?

In [9]:
original_array = np.array([[1, 2, 3, 4, 5],
                           [6, 7, 8, 9, 10],
                           [11, 12, 13, 14, 15],
                           [16, 17, 18, 19, 20],
                           [21, 22, 23, 24, 25]])

# Find the square of each element in the array
square_array = np.square(original_array)

print("Original Array:")
print(original_array)
print("\nArray after squaring each element:")
print(square_array)

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array after squaring each element:
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]
 [441 484 529 576 625]]


### Question:8

### Create 5x6 an array and find the mean?

In [10]:
array_5x6 = np.array([[1, 2, 3, 4, 5, 6],
                      [7, 8, 9, 10, 11, 12],
                      [13, 14, 15, 16, 17, 18],
                      [19, 20, 21, 22, 23, 24],
                      [25, 26, 27, 28, 29, 30]])

# Calculate the mean of the array
mean_value = np.mean(array_5x6)

print("Original 5x6 Array:")
print(array_5x6)
print("\nMean of the Array:", mean_value)

Original 5x6 Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Mean of the Array: 15.5


### Question:9

### Find the standard deviation of the previous array in Q8?

In [11]:
std_deviation_value = np.std(array_5x6)

print("Original 5x6 Array:")
print(array_5x6)
print("\nStandard Deviation of the Array:", std_deviation_value)

Original 5x6 Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Standard Deviation of the Array: 8.65544144839919


### Question:10

### Find the median of the previous array in Q8?

In [12]:
median_value = np.median(array_5x6)

print("Original 5x6 Array:")
print(array_5x6)
print("\nMedian of the Array:", median_value)

Original 5x6 Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Median of the Array: 15.5


### Question:11

### Find the transpose of the previous array in Q8?

In [13]:
transpose_array = np.transpose(array_5x6)  # or array_5x6.T

print("Original 5x6 Array:")
print(array_5x6)
print("\nTranspose of the Array:")
print(transpose_array)

Original 5x6 Array:
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]]

Transpose of the Array:
[[ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]
 [ 6 12 18 24 30]]


### Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [14]:
array_4x4 = np.array([[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12],
                      [13, 14, 15, 16]])

# Find the sum of diagonal elements
diagonal_sum = np.trace(array_4x4)

print("Original 4x4 Array:")
print(array_4x4)
print("\nSum of Diagonal Elements:", diagonal_sum)

Original 4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Sum of Diagonal Elements: 34


### Question:13

### Find the determinant of the previous array in Q12?

In [15]:
determinant_value = np.linalg.det(array_4x4)

print("Original 4x4 Array:")
print(array_4x4)
print("\nDeterminant of the Array:", determinant_value)

Original 4x4 Array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Determinant of the Array: -1.820448242817726e-31


### Question:14

### Find the 5th and 95th percentile of an array?

In [16]:
# Create an example array
example_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Calculate the 5th and 95th percentiles
percentile_5th = np.percentile(example_array, 5)
percentile_95th = np.percentile(example_array, 95)

print("Original Array:")
print(example_array)
print("\n5th Percentile:", percentile_5th)
print("95th Percentile:", percentile_95th)

Original Array:
[ 1  2  3  4  5  6  7  8  9 10]

5th Percentile: 1.45
95th Percentile: 9.549999999999999


### Question:15

### How to find if a given array has any null values?

In [17]:
# Create an example array with null values
example_array = np.array([1, 2, np.nan, 4, 5, 6, np.nan, 8, 9, 10])

# Check if the array has any null values
has_null_values = np.any(np.isnan(example_array))

if has_null_values:
    print("The array has null values.")
else:
    print("The array does not have any null values.")

The array has null values.
