In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [4]:
a = np.array([1,2,3,4,5], ndmin=2)
print(a)

[[1 2 3 4 5]]


In [5]:
a = np.array([1,2,3], dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]


In [6]:
# using array-scalar type

dt = np.dtype(np.int32)
print(dt)

int32


In [7]:
# first create structured data type

dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [8]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10),(20),(30)], dtype=dt)
print(a)


[(10,) (20,) (30,)]


In [9]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10),(20),(30)], dtype=dt)
print(a['age'])


[10 20 30]


In [10]:
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
print(student)

[('name', 'S20'), ('age', 'i1'), ('marks', '<f4')]


In [11]:
student = np.dtype([('name','S20'),('age','i1'),('marks','f4')])
a = np.array([('abc',21,50),('xyz',18,75)], dtype=student)
print(a)

[(b'abc', 21, 50.) (b'xyz', 18, 75.)]
