### Numpy

* Numerical Python
* Fastest
* Vectorised Operation
* Contiguous Memory

In [1]:
import numpy as np

In [4]:
x = np.array([11,22,33,44,55])
# Creating an array using python list

In [5]:
x

array([11, 22, 33, 44, 55])

In [6]:
x.size

5

In [7]:
# 1d = Vector
# 2d = Matrix
# 3d = Cube
# ND = .....
x.shape

(5,)

In [8]:
x.ndim

1

In [10]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
arr1d = np.arange(10)

In [11]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2d = np.array([[1,2,3],[11,22,33],[111,222,333],[1111,2222,3333],[11111,22222,33333]])

In [13]:
arr2d

array([[    1,     2,     3],
       [   11,    22,    33],
       [  111,   222,   333],
       [ 1111,  2222,  3333],
       [11111, 22222, 33333]])

In [14]:
arr2d.shape

(5, 3)

In [33]:
arr2d = np.arange(20).reshape(2,10)

In [34]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [35]:
arr2d.shape

(2, 10)

In [36]:
arr2d.ndim

2

In [37]:
arr2d.reshape(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [38]:
arr2d.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
arr2d.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [40]:
arr3d = np.arange(64).reshape(4,4,4) # (depth , row , columns)
                                     # (matrixnum,row,columns) According to ML

In [41]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [42]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [43]:
arr2d[1,6]

16

In [44]:
arr2d[1][6]

16

In [45]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [46]:
arr3d[0,2,2]

10

In [47]:
arr3d[1,3,3]

31

In [48]:
arr3d[2,2,1]

41

In [49]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr1d * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])