In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
b = np.array([10,20,30,40])
c = a * b
c

array([ 10,  40,  90, 160])

In [3]:
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print("First Array :")
print(a)
print("/n")

print("Second Array :")
print(b)
print("/n")

print("First Array + Second Array:")
print(a + b)
print("/n")

First Array :
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
/n
Second Array :
[1. 2. 3.]
/n
First Array + Second Array:
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]
/n


#### Itearting over array

In [4]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print("Original Array is:")
print(a)
print("\n")

print("Modified Array is:")
for x in np.nditer(a):
    print(x)


Original Array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified Array is:
0
5
10
15
20
25
30
35
40
45
50
55


In [5]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print("Original Array is:")
print(a)
print("\n")

print("Transpose of Array is:")
b = a.T
print(b)
print("\n")

print("Modified Array is:")
for x in np.nditer(b):
    print(x)

Original Array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of Array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Modified Array is:
0
5
10
15
20
25
30
35
40
45
50
55


#### Iteration Order

In [6]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print("Original Array is:")
print(a)
print("\n")

print("Transpose of Array is:")
b = a.T
print(b)
print("\n")

print("Sorted in C-style order:")
c = b.copy(order = "C")
print(c)
for x in np.nditer(c):
    print(x)

print("\n")

print("Sorted in F-style order:")
c = b.copy(order = "F")
print(c)
for x in np.nditer(c):
    print(x)

Original Array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of Array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


In [7]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print("Original Array is:")
print(a)
print("\n")

print("Sorted in C-style order:")
c = b.copy(order = "C")
print(c)
for x in np.nditer(c):
    print(x)

print("\n")

print("Sorted in F-style order:")
c = b.copy(order = "F")
print(c)
for x in np.nditer(c):
    print(x)

Original Array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


#### Modifying Array Values

In [8]:
a = np.arange(0,60,5)
a = a.reshape(3,4)

print("Original Array is:")
print(a)
print("\n")

for x in np.nditer(a, op_flags=['readwrite']):
    x[...] = 2 * x

print("Modified Array is :")
print(a)    



Original Array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified Array is :
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]
