In [1]:
import numpy as np

In [3]:
a = np.array([1,256,8755], dtype= int)

print("Our array is")
print(a)

print("Representation of Data in memory in hexadecimal form :")
print(map(hex,a))

# byteswap() function swaps in place by passing True parameter

print("Applying byteswap() function :")
print(a.byteswap(True))

print("In hexadecimal form :")
print(map(hex,a))

# we can see the bytes being swapped

Our array is
[   1  256 8755]
Representation of Data in memory in hexadecimal form :
Applying byteswap() function :
[ 16777216     65536 857866240]
In hexadecimal form :


### Copy and View

#### No Copy

In [4]:
a = np.arange(6)

print("Our array is")
print(a)

print("Applying id() function :")
print(id(a))

print("a is assigned to b")

b = a
print(b)

print("b has same id :")
print(id(b))

print("Change shape of b :")
b.shape = 3,2
print(b)

print(a)

Our array is
[0 1 2 3 4 5]
Applying id() function :
2226375474992
a is assigned to b
[0 1 2 3 4 5]
b has same id :
2226375474992
Change shape of b :
[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]


### View or Shallow Copy

In [5]:
a = np.arange(6).reshape(3,2)

print(a)

b = (a.view())
print(b)

print(id(a))
print(id(b))



[[0 1]
 [2 3]
 [4 5]]
[[0 1]
 [2 3]
 [4 5]]
2226379649360
2226379648496


### Deep Copy

In [6]:
a = np.array([[10,10],[2,3],[4,5]])

print(a)

b = a.copy()

print(b)

print(b is a)

b[0,0] = 100

print(b)

print(a)

[[10 10]
 [ 2  3]
 [ 4  5]]
[[10 10]
 [ 2  3]
 [ 4  5]]
False
[[100  10]
 [  2   3]
 [  4   5]]
[[10 10]
 [ 2  3]
 [ 4  5]]
