## **Assignment For Numpy**

### Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
v.shape

(40,)

5. Print the type of the previous array in question 3

In [6]:
type(v)

numpy.ndarray

6. Print the numpy version and the configuration


In [7]:
# Print NumPy version
print("NumPy Version:", np.__version__)

# Print NumPy configuration
print("\nNumPy Configuration:")
print(np.show_config())

NumPy Version: 1.24.3

NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Use

7. Print the dimension of the array in question 3


In [8]:
v.shape

(40,)

8. Create a boolean array with all the True values

In [9]:
boolean_array = np.ones(10, dtype= bool)
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array

In [10]:
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])

print(two_dimensional_array)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [11]:
three_dimensional_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(three_dimensional_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

12. Create a null vector of size 10 but the fifth value which is 1 

13. Create a 3x3 identity matrix

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

15. arr1 =          np.array([[1., 2., 3.],[4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

---


Multiply arr1 with arr2
