## **Assignment For Numpy**

### Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
v.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
type(v)

numpy.ndarray

6. Print the numpy version and the configuration


In [6]:
# Print NumPy version
print("NumPy Version:", np.__version__)

# Print NumPy configuration
print("\nNumPy Configuration:")
print(np.show_config())

NumPy Version: 1.24.3

NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Use

7. Print the dimension of the array in question 3


In [7]:
v.shape

(40,)

8. Create a boolean array with all the True values

In [8]:
boolean_array = np.ones(10, dtype= bool)
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array

In [9]:
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])

print(two_dimensional_array)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [10]:
three_dimensional_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(three_dimensional_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
a = np.array([1,2,3,4,5])
b = a[::-1]
print(a)
b

[1 2 3 4 5]


array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1,2,3,4,5])
arr = arr.astype(float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],[4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr = arr1 * arr2
arr

array([[ 0,  8,  3],
       [28, 10, 72]])

16. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.],  [7., 2., 12.]])

---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr = arr1 - arr2
arr

array([[ 1, -2,  2],
       [-3,  3, -6]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr3 = np.arange(1,10,2)
arr3

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr3[:] = -1
arr3

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
rows , cols = 5,5

array_2d = np.ones((rows,cols), dtype = int)
array_2d[1:-1,1:-1] = 0
array_2d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d [0,:,:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
first_row = arr[0,:] 
first_row

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
second_row = arr[1,:] 
second_row

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
third_column = arr[:2,2] 
third_column

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [27]:
arr = np.random.rand(10,10)
print(arr)

min_value = np.min(arr)
max_value = np.max(arr)

print(min_value)
print(max_value)

[[0.19869759 0.86853855 0.34367434 0.87729759 0.36461968 0.21045675
  0.88540998 0.71148858 0.00920492 0.67249703]
 [0.53960322 0.77951374 0.51252686 0.62990245 0.68365371 0.69870789
  0.45269391 0.26769579 0.7561954  0.21995365]
 [0.97741415 0.86125529 0.74920719 0.94389291 0.64025099 0.4884217
  0.33080637 0.66228534 0.76184571 0.96063188]
 [0.31962085 0.65491471 0.34813589 0.6025918  0.85569838 0.05122284
  0.76850205 0.15366449 0.15167392 0.8434589 ]
 [0.65943174 0.82309073 0.77435293 0.17704047 0.11892732 0.5396247
  0.22856219 0.39237614 0.54751382 0.55996302]
 [0.30889331 0.50071831 0.02993886 0.41590255 0.29743792 0.05197846
  0.71866484 0.41003216 0.05644209 0.16791917]
 [0.40273433 0.16627829 0.04986463 0.10633446 0.11758128 0.62802383
  0.6658497  0.12499898 0.89496808 0.93330786]
 [0.05085054 0.54235274 0.24824428 0.48175214 0.29564821 0.90830648
  0.79066494 0.22751296 0.51156497 0.17845247]
 [0.20814061 0.84087924 0.73729016 0.12119912 0.03880005 0.26868529
  0.36534627 0

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_items = np.intersect1d(a,b)
print(common_items)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the positions where elements of a and b match



In [29]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

matching_positions = np.where(a == b)
print(matching_positions)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



## Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


40. Generate a matrix of 20 random values and find its cumulative sum