## **Assignment For Numpy**

### Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [3]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
v.shape

(40,)

5. Print the type of the previous array in question 3

In [5]:
type(v)

numpy.ndarray

6. Print the numpy version and the configuration


In [6]:
# Print NumPy version
print("NumPy Version:", np.__version__)

# Print NumPy configuration
print("\nNumPy Configuration:")
print(np.show_config())

NumPy Version: 1.24.3

NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Use

7. Print the dimension of the array in question 3


In [7]:
v.shape

(40,)

8. Create a boolean array with all the True values

In [8]:
boolean_array = np.ones(10, dtype= bool)
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array

In [9]:
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])

print(two_dimensional_array)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [10]:
three_dimensional_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(three_dimensional_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
a = np.array([1,2,3,4,5])
b = a[::-1]
print(a)
b

[1 2 3 4 5]


array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [12]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [13]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [14]:
arr = np.array([1,2,3,4,5])
arr = arr.astype(float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],[4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

---


Multiply arr1 with arr2


In [15]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr = arr1 * arr2
arr

array([[ 0,  8,  3],
       [28, 10, 72]])

16. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.],  [7., 2., 12.]])

---

Make an array by comparing both the arrays provided above

In [16]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr = arr1 - arr2
arr

array([[ 1, -2,  2],
       [-3,  3, -6]])

17. Extract all odd numbers from arr with values(0-9)

In [17]:
arr3 = np.arange(1,10,2)
arr3

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [18]:
arr3[:] = -1
arr3

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [19]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [20]:
rows , cols = 5,5

array_2d = np.ones((rows,cols), dtype = int)
array_2d[1:-1,1:-1] = 0
array_2d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

---

Replace the value 5 to 12

In [21]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [22]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d [0,:,:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [23]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
first_row = arr[0,:] 
first_row

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [24]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
second_row = arr[1,:] 
second_row

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [25]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
third_column = arr[:2,2] 
third_column

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [26]:
arr = np.random.rand(10,10)
print(arr)

min_value = np.min(arr)
max_value = np.max(arr)

print(min_value)
print(max_value)

[[0.42861226 0.04985712 0.09883044 0.13294038 0.33103562 0.94207062
  0.67852071 0.22993476 0.86963632 0.68018116]
 [0.59283348 0.6117367  0.96047297 0.57721217 0.07205396 0.30082183
  0.43423302 0.37559258 0.52992097 0.73369579]
 [0.14651201 0.59521153 0.78311742 0.82503697 0.80162283 0.96100499
  0.79376216 0.65911093 0.73907932 0.5809861 ]
 [0.76754358 0.55176424 0.8632292  0.54990244 0.93383733 0.19463232
  0.94640548 0.15172766 0.72138731 0.35950854]
 [0.79316091 0.37108129 0.43541297 0.91880861 0.12333561 0.88420753
  0.84091131 0.19864139 0.73771238 0.88340644]
 [0.89182945 0.86624763 0.28428998 0.43533998 0.25593949 0.96873158
  0.38836703 0.47467452 0.74960065 0.23596239]
 [0.89144892 0.19429645 0.29807912 0.7475901  0.27098983 0.83919791
  0.03157477 0.01870489 0.87975288 0.75683976]
 [0.293849   0.87635042 0.8489658  0.77367633 0.458037   0.79655281
  0.44516762 0.26999629 0.26689687 0.94509434]
 [0.63520073 0.75505319 0.66030119 0.7744905  0.87742421 0.45611898
  0.36621156

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [27]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

common_items = np.intersect1d(a,b)
print(common_items)

[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the positions where elements of a and b match



In [28]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

matching_positions = np.where(a == b)
print(matching_positions)

(array([1, 3, 5, 7], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [29]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

# Find indices where names are not equal to 'Will'
mask = names != 'Will' 

# Use the mask to filter data
result = data[mask]

print(result)

[[ 0.02117319 -1.49146655 -0.99713105 -2.11123618]
 [-0.10758371  1.21798963  1.07346998  0.62092701]
 [-2.02141145  0.52371084  0.08496148  0.37831777]
 [-0.13559787 -0.70711489  0.27387908 -0.70666854]
 [ 0.56894148  1.17943127  0.81943561  0.42753019]]


30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [33]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)

# Find indices where names are not equal to 'Will'
mask = (names != 'Will') & (names != 'Joe')

# Use the mask to filter data
result = data[mask]

print(result)

[[-0.68228695 -0.94654822 -0.52061903 -0.13373894]
 [ 0.20117851 -1.52452335  0.00987236  0.01035302]]


## Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [34]:
array_2d = np.random.uniform(1.0, 15.0, size=(5, 3))

print(array_2d)

[[ 1.56829097  6.96619702 13.65952741]
 [ 1.74822487  3.56019058  8.70504539]
 [13.75229024  3.29738686  3.94223989]
 [11.72734887  5.64654029  9.14825712]
 [ 5.61467269  8.33040348 10.71240056]]


32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [35]:
array_3d = np.random.uniform(1.0, 16.0, size=(2, 2, 4))

print(array_3d)

[[[12.89077624 10.82872122  4.38513437  3.66025241]
  [ 3.31779599  8.63785785  8.00567064 13.69563777]]

 [[ 9.07624695 11.7643627  12.7819358  15.69056877]
  [ 1.54437496  9.93267184  6.34594567  9.03957943]]]


33. Swap axes of the array you created in Question 32

In [36]:
array_3d_swapped = np.swapaxes(array_3d, 0, 2)
print(array_3d_swapped)

[[[12.89077624  9.07624695]
  [ 3.31779599  1.54437496]]

 [[10.82872122 11.7643627 ]
  [ 8.63785785  9.93267184]]

 [[ 4.38513437 12.7819358 ]
  [ 8.00567064  6.34594567]]

 [[ 3.66025241 15.69056877]
  [13.69563777  9.03957943]]]


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [37]:
# Create an array of size 10
original_array = np.random.rand(10)

# Find the square root of every element
sqrt_array = np.sqrt(original_array)

# Replace values less than 0.5 with 0
sqrt_array[sqrt_array < 0.5] = 0

print("Original Array:")
print(original_array)

print("\nSquare Root Array with Values >= 0.5:")
print(sqrt_array)

Original Array:
[0.28489854 0.86029273 0.43987642 0.50783277 0.79546047 0.52517699
 0.64345427 0.98136742 0.46762706 0.14423503]

Square Root Array with Values >= 0.5:
[0.53375888 0.92751966 0.6632318  0.71262387 0.89188591 0.72469096
 0.80215601 0.9906399  0.68383262 0.        ]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [38]:

# Create two random arrays of size 12
array1 = np.random.rand(12)
array2 = np.random.rand(12)

# Create an array with the maximum values between corresponding elements
max_values_array = np.maximum(array1, array2)

print("Array 1:")
print(array1)

print("\nArray 2:")
print(array2)

print("\nArray with Maximum Values:")
print(max_values_array)

Array 1:
[0.84989428 0.89121565 0.73730662 0.1847254  0.83711307 0.44189914
 0.88338212 0.64016536 0.83848614 0.23981331 0.92092154 0.79457274]

Array 2:
[0.07622183 0.86328142 0.51674551 0.78812279 0.81244503 0.59665755
 0.68226026 0.57231091 0.98456784 0.65175478 0.94486586 0.79255632]

Array with Maximum Values:
[0.84989428 0.89121565 0.73730662 0.78812279 0.83711307 0.59665755
 0.88338212 0.64016536 0.98456784 0.65175478 0.94486586 0.79457274]


36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [39]:

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

# Find unique names
unique_names = np.unique(names)

# Sort the unique names
sorted_unique_names = np.sort(unique_names)

print("Original Names:")
print(names)

print("\nUnique and Sorted Names:")
print(sorted_unique_names)

Original Names:
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']

Unique and Sorted Names:
['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [40]:

a = np.array([1, 2, 3, 4, 5])
b = np.array([5, 6, 7, 8, 9])

# Find the set difference between a and b
result = np.setdiff1d(a, b)

print("Array a:")
print(a)

print("\nArray b:")
print(b)

print("\nResult after removing items from a present in b:")
print(result)

Array a:
[1 2 3 4 5]

Array b:
[5 6 7 8 9]

Result after removing items from a present in b:
[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [41]:

sampleArray = np.array([[34, 43, 73], [82, 22, 12], [53, 94, 66]])
newColumn = np.array([[10, 10, 10]])

# Delete the second column (axis=1)
sampleArray = np.delete(sampleArray, 1, axis=1)

# Insert the new column at the second position
sampleArray = np.insert(sampleArray, 1, newColumn, axis=1)

print("Original Array:")
print(sampleArray)

Original Array:
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [42]:

x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])

# Calculate the dot product using np.dot()
dot_product_result = np.dot(x, y)

# Alternatively, you can use the @ operator for matrix multiplication
# dot_product_result = x @ y

print("Matrix x:")
print(x)

print("\nMatrix y:")
print(y)

print("\nDot Product Result:")
print(dot_product_result)


Matrix x:
[[1. 2. 3.]
 [4. 5. 6.]]

Matrix y:
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]

Dot Product Result:
[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [43]:
# Generate a matrix of 20 random values
random_matrix = np.random.rand(4, 5)

print("Original Matrix:")
print(random_matrix)

# Find the cumulative sum along each axis
cumulative_sum_matrix = np.cumsum(random_matrix)

print("\nCumulative Sum Matrix:")
print(cumulative_sum_matrix)

Original Matrix:
[[0.93334018 0.42851256 0.409721   0.87905324 0.34254942]
 [0.0270257  0.53348608 0.13437071 0.99293905 0.84961289]
 [0.76578648 0.75021247 0.54625562 0.62150845 0.01335809]
 [0.60452001 0.8672613  0.86756325 0.16624251 0.73978362]]

Cumulative Sum Matrix:
[ 0.93334018  1.36185274  1.77157374  2.65062699  2.9931764   3.0202021
  3.55368818  3.68805889  4.68099794  5.53061083  6.29639731  7.04660978
  7.59286539  8.21437384  8.22773193  8.83225195  9.69951325 10.56707649
 10.73331901 11.47310262]
