## **Assignment For Numpy**

### Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [62]:
import numpy as np

2. Create a null vector of size 10 

In [63]:
null_vector = np.zeros(10)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [64]:
v = np.arange(10,50)
v

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [65]:
v.shape

(40,)

5. Print the type of the previous array in question 3

In [66]:
type(v)

numpy.ndarray

6. Print the numpy version and the configuration


In [67]:
# Print NumPy version
print("NumPy Version:", np.__version__)

# Print NumPy configuration
print("\nNumPy Configuration:")
print(np.show_config())

NumPy Version: 1.24.3

NumPy Configuration:
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/SC/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SC/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Use

7. Print the dimension of the array in question 3


In [68]:
v.shape

(40,)

8. Create a boolean array with all the True values

In [69]:
boolean_array = np.ones(10, dtype= bool)
boolean_array

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array

In [70]:
two_dimensional_array = np.array([[1, 2, 3], [4, 5, 6]])

print(two_dimensional_array)

[[1 2 3]
 [4 5 6]]


10. Create a three dimensional array



In [71]:
three_dimensional_array = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(three_dimensional_array)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [72]:
a = np.array([1,2,3,4,5])
b = a[::-1]
print(a)
b

[1 2 3 4 5]


array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [73]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [74]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [75]:
arr = np.array([1,2,3,4,5])
arr = arr.astype(float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],[4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],[7., 2., 12.]])

---


Multiply arr1 with arr2


In [76]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr = arr1 * arr2
arr

array([[ 0,  8,  3],
       [28, 10, 72]])

16. arr1 = np.array([[1., 2., 3.], [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.],  [7., 2., 12.]])

---

Make an array by comparing both the arrays provided above

In [77]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr = arr1 - arr2
arr

array([[ 1, -2,  2],
       [-3,  3, -6]])

17. Extract all odd numbers from arr with values(0-9)

In [78]:
arr3 = np.arange(1,10,2)
arr3

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [79]:
arr3[:] = -1
arr3

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [80]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [81]:
rows , cols = 5,5

array_2d = np.ones((rows,cols), dtype = int)
array_2d[1:-1,1:-1] = 0
array_2d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

---

Replace the value 5 to 12

In [82]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [83]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d [0,:,:] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [85]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
first_row = arr[0,:] 
first_row

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [86]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
second_row = arr[1,:] 
second_row

array([5, 6, 7, 8, 9])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [87]:
arr = np.array([[0,1,2,3,4],[5,6,7,8,9]])
third_column = arr[:2,2] 
third_column

array([2, 7])

26. Create a 10x10 array with random values and find the minimum and maximum values

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b
