### Q1:

In [1]:
import numpy as np

arr = np.diag(np.arange(10))

print(arr)

[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 3 0 0 0 0 0 0]
 [0 0 0 0 4 0 0 0 0 0]
 [0 0 0 0 0 5 0 0 0 0]
 [0 0 0 0 0 0 6 0 0 0]
 [0 0 0 0 0 0 0 7 0 0]
 [0 0 0 0 0 0 0 0 8 0]
 [0 0 0 0 0 0 0 0 0 9]]


### Q2:

In [3]:
arr = np.ones(shape=(4,4), dtype="int")
arr = np.pad(arr * 5, pad_width=1, constant_values=0)
print(arr)

[[0 0 0 0 0 0]
 [0 5 5 5 5 0]
 [0 5 5 5 5 0]
 [0 5 5 5 5 0]
 [0 5 5 5 5 0]
 [0 0 0 0 0 0]]


### Q3:

In [7]:
arr = np.zeros(shape=(6,6), dtype="int")
arr[::2,::2] = 2
arr[1::2,::2] = 4

print(arr)

[[2 0 2 0 2 0]
 [4 0 4 0 4 0]
 [2 0 2 0 2 0]
 [4 0 4 0 4 0]
 [2 0 2 0 2 0]
 [4 0 4 0 4 0]]


### Q4:

In [9]:
arr = np.array( 
    [
        [4.99,3.49,9.99],
        [1.99,9.99,14.99],
        [14.99,2.39,7.29],
    ]
)

result = np.zeros_like(arr)
print(result)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


### Q5:

In [10]:
arr = np.array( 
    [
        [4.99,3.49,9.99],
        [1.99,9.99,14.99],
        [14.99,2.39,7.29],
    ]
)

result = np.full_like(arr,9.99)
print(result)

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


### Q6:

In [11]:
arr = np.tri(N=6)
print(arr)

[[1. 0. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1. 1.]]


### Q7:

In [12]:
arr = np.array(
    [
        [False,True,True,False,True],
        [False,False,True,True,True]
    ]
)

arr = arr.astype("int")
print(arr)

[[0 1 1 0 1]
 [0 0 1 1 1]]


### Q8:

In [15]:
arr = np.array([[4,5,67,8,2,4],[4,2,5,7,2,5]], dtype="int32")
print(arr)

[[ 4  5 67  8  2  4]
 [ 4  2  5  7  2  5]]
