## Exercise 1
#### Using NumPy create a 5x5 array filled with zeros (set data type to int16) and assign it to a variable named arr. In response, print this array to the console.

In [1]:
import numpy as np

In [2]:
arr = np.zeros(shape = (5,5), dtype= "int16")

print(arr)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


## Exercise 2

#### Using NumPy, create a 10x10 array filled with number 8 (set the data type to float32) and assign it to a variable named arr. In response, print this array to the console as shown below.

In [3]:
import numpy as np

In [6]:
arr = np.full(shape=(10,10), fill_value=8, dtype="float32")

print(arr)

[[8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]
 [8. 8. 8. 8. 8. 8. 8. 8. 8. 8.]]


### Exercise 3
#### Using NumPy, create a one-dimensional array of all two-digit numbers, assign it to a variable named arr and print this array to the console as shown below.

In [7]:
import numpy as np

In [8]:
arr = np.arange(10,100)

print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


### Exercise 4
#### Using NumPy create the following array:



 [[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


#### Note that the shape of this array is (9, 10). In response, print this array to the console.

In [9]:
import numpy as np

In [10]:
arr = np.arange(10,100).reshape(9,10)

print(arr)

[[10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


### Exercise 5
#### Using NumPy, create a 8x8 two-dimensional array - identity matrix with int16 data type and assign it to a variable named arr. In response, print this array to the console as shown below.

In [11]:
import numpy as np

In [13]:
arr = np.eye(N = 8, dtype="int16")

print(arr)

[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


### Exercise 6
#### Using NumPy create any 3-dimensional array of the shape (2, 3, 4) and assign it to variable arr.

In [14]:
import numpy as np
 
 
arr = np.array(
    [
        [
            [4, 5, 4, 2],
            [6, 3, 5, 1],
            [5, 2, 1, 2],
        ],
        [
            [7, 2, 3, 1],
            [6, 2, 0, 9],
            [0, 1, 9, 1],
        ],
    ]
)

In [15]:
arr

array([[[4, 5, 4, 2],
        [6, 3, 5, 1],
        [5, 2, 1, 2]],

       [[7, 2, 3, 1],
        [6, 2, 0, 9],
        [0, 1, 9, 1]]])

### Exercise 7
#### Suppose you have the following NumPy array:



arr = np.array(
    [
        ['4', '3', '6', '2', '1'],
        ['7', '2', '1', '2', '6'],
    ],
    dtype='<U1',
)


Change the data type of this array to float16. In response print this array to the console

In [16]:
import numpy as np
 
 
arr = np.array(
    [
        ['4', '3', '6', '2', '1'],
        ['7', '2', '1', '2', '6'],
    ],
    dtype='<U1',
)
 
arr = arr.astype('float16')
print(arr)

[[4. 3. 6. 2. 1.]
 [7. 2. 1. 2. 6.]]


### Exercise 8
#### Create any one-dimensional NumPy array of the shape (5,) and assign it to variable named arr.

In [17]:
import numpy as np
 
 
arr = np.array([4, 5, 67, 8, 2])

In [18]:
arr

array([ 4,  5, 67,  8,  2])