In [1]:
import numpy as np

#### np.sort()

In [2]:
a = np.array([[3,7],[9,1]])

print("Our array is :")
print(a)
print("\n")

print("Applying sort() function :")
print(np.sort(a))
print("\n")

print("Applying sort() function along 0 axis :")
print(np.sort(a, axis=0))
print("\n")

# order parameter in sort function

dt = (np.dtype([('name','S10'),('age',int)]))
a = (np.array([('raju',21),('anil',25),('ravi',17),('amar',27)], dtype=dt))

print("Our array is :")
print(a)
print("\n")

print(np.sort(a,order = 'name'))

Our array is :
[[3 7]
 [9 1]]


Applying sort() function :
[[3 7]
 [1 9]]


Applying sort() function along 0 axis :
[[3 1]
 [9 7]]


Our array is :
[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


#### np.where()

In [3]:
x = np.arange(9).reshape(3,3)
print("Our array is :")
print(x)
print("Indices of elements > 3")
y = np.where(x > 3)
print(y)

print(x[y])

Our array is :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
Indices of elements > 3
(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))
[4 5 6 7 8]


#### np.extract()

In [4]:
x = np.arange(9).reshape(3,3)
print("Our array is :")
print(x)

conndition = np.mod(x,2) == 0
print(conndition)

print(np.extract(conndition,x))

Our array is :
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ True False  True]
 [False  True False]
 [ True False  True]]
[0 2 4 6 8]
