In [7]:
import numpy as np

#### numpy.asarray

In [8]:
x = [1,2,3]
a = np.asarray(x)
print(a)

[1 2 3]


In [9]:
x = [1,2,3]
a = np.asarray(x, dtype= float)
print(a)

[1. 2. 3.]


In [10]:
x = (1,2,3)
a = np.asarray(x)
print(a)

[1 2 3]


In [19]:
# ndarray from list of tuples

x = ([(1,2,3),(4,5)])
a = np.asarray(x)
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

#### numpy.fromiter

In [20]:
list = range(5)
it = iter(list)

x = np.fromiter(it, dtype= float)
print(x)

[0. 1. 2. 3. 4.]


#### numpy.arange

In [21]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [22]:
x = np.arange(5, dtype= float)
print(x)

[0. 1. 2. 3. 4.]


In [23]:
x = np.arange(10,20,2)
print(x)

[10 12 14 16 18]


#### numpy.linspace

In [24]:
x = np.linspace(10,20,5)
print(x)

[10.  12.5 15.  17.5 20. ]


In [25]:
x = np.linspace(10,20,5, endpoint=False)
print(x)

[10. 12. 14. 16. 18.]


In [27]:
x = np.linspace(1,2,5, retstep= True)
print(x)

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)


#### numpy.logspace

In [28]:
a = np.logspace(1.0,2.0, num = 10)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [29]:
a = np.logspace(1,10, num = 10, base = 2)
print(a)

[   2.    4.    8.   16.   32.   64.  128.  256.  512. 1024.]
