In [1]:
import numpy as np

#### ndarray.shape

In [2]:
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)

(2, 3)


In [3]:
a = np.array([[1,2,3],[4,5,6]])
a.shape = (3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [5]:
a = np.array([[1,2,3],[4,5,6]])
b = a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


#### ndarray.ndim

In [6]:
a = np.arange(24)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [10]:
a = np.arange(24)
print(a.ndim)
# reshape

b = a.reshape(2,4,3)
print(b)

1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


#### numpy.itemsize

In [11]:
x = np.array([1,2,3,4,5], dtype=np.int8)
print(x.itemsize)

1


In [12]:
x = np.array([1,2,3,4,5], dtype=np.float32)
print(x.itemsize)

4


#### numpy.flags

In [13]:
x = np.array([1,2,3,4,5])
print(x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



### Array Creation Routines

#### numpy.empty

In [14]:
# numpy.empty(shape, dtype=float, order = 'C')

In [17]:
x = np.empty([3,2], dtype = 'int')
print(x)

[[1 2]
 [3 4]
 [5 6]]


#### numpy.zeros

In [18]:
x = np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [21]:
x = np.zeros((5), dtype = int)
print(x)

[0 0 0 0 0]


In [22]:
x = np.zeros((2,2), dtype= [('x','i4'), ('y','i4')])
print(x)

[[(0, 0) (0, 0)]
 [(0, 0) (0, 0)]]


#### numpy.ones

In [23]:
x = np.ones(5)
print(x)

[1. 1. 1. 1. 1.]


In [24]:
x = np.ones([2,2], dtype= int)
print(x)

[[1 1]
 [1 1]]
